# Generated by Django 5.1.5 on 2025-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-university')", max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('light', 'Light')], default='primary', max_length=50)),
            ],
        ),
    ]
