# Generated by Django 5.1.5 on 2025-02-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_fact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
