# Generated by Django 5.1.5 on 2025-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_teammember_options_teammember_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GoWell Consultancy', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.CharField(default='Lamahi-5, Dang, Nepal', max_length=255)),
                ('phone', models.CharField(default='+977 9845293203', max_length=20)),
                ('email', models.EmailField(default='info@gowell.edu.np', max_length=254)),
                ('about', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
