# Generated by Django 5.1.5 on 2025-02-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_faq_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_name',
            new_name='name',
        ),
    ]
