# Generated by Django 5.2.3 on 2025-06-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_client_name_testimonial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='twitter',
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text="Font Awesome class, e.g., 'fab fa-twitter fw-normal'", max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='website.companyinfo')),
            ],
        ),
    ]
